-- StockPulse seed data (Addendum A, adapted to the JPA-generated schema)
-- PRD-003 (T-Shirt): stock 8, threshold 15 -- already low, good for an immediate demo
-- PRD-008 (Hoodie): stock 11, threshold 12, velocity 15 -- demand-spike demo via POST /api/products/PRD-008/orders

INSERT INTO products (id, sku, name, category, current_price, stock_level, reorder_threshold, demand_velocity, status, cost_price, supplier_id, created_at, updated_at) VALUES
  ('PRD-001', 'SKU-ELEC-001', 'Wireless Earbuds Pro',    'ELECTRONICS', 79.99, 45,  20, 3,  'ACTIVE',               NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('PRD-002', 'SKU-ELEC-002', 'USB-C Hub 7-Port',        'ELECTRONICS', 34.99, 120, 30, 1,  'ACTIVE',               NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('PRD-003', 'SKU-APP-001',  'Organic Cotton T-Shirt',  'APPAREL',     24.99, 8,   15, 12, 'PRICE_REVIEW_PENDING', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('PRD-004', 'SKU-APP-002',  'Running Shorts - Navy',   'APPAREL',     39.99, 55,  20, 2,  'ACTIVE',               NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('PRD-005', 'SKU-HOME-001', 'Ceramic Pour-Over Set',   'HOME',        49.99, 22,  10, 4,  'ACTIVE',               NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('PRD-006', 'SKU-HOME-002', 'LED Desk Lamp - Dimmable','HOME',        59.99, 0,   15, 0,  'OUT_OF_STOCK',         NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('PRD-007', 'SKU-ELEC-003', 'Portable Charger 20K',    'ELECTRONICS', 44.99, 18,  25, 8,  'ACTIVE',               NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('PRD-008', 'SKU-APP-003',  'Hoodie - Heather Grey',   'APPAREL',     54.99, 11,  12, 15, 'ACTIVE',               NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- PRD-003 already sits below its reorder threshold, so it ships with a pending pricing
-- suggestion seeded to mirror the PRICE_REVIEW_PENDING status above (id is a string PK,
-- picked manually since no suggestion has been generated by the app yet).
INSERT INTO pricing_suggestions (id, product_id, current_price_at_suggestion, recommended_price, change_direction, confidence, reasoning, status, trigger_reason, generated_by, created_at, decided_at) VALUES
  ('PS-SEED-001', 'PRD-003', 24.99, 27.49, 'INCREASE', 0.75, 'Seed data: stock (8) is below the reorder threshold (15); a modest increase protects remaining inventory while a reorder is arranged.', 'PENDING', 'INVENTORY_LOW', 'RULE_BASED', CURRENT_TIMESTAMP, NULL);

INSERT INTO reorder_suggestions (id, product_id, current_stock_at_suggestion, recommended_quantity, suggested_lead_time_days, confidence, reasoning, status, trigger_reason, generated_by, created_at, decided_at) VALUES
  ('RS-SEED-001', 'PRD-003', 8, 37, 7, 0.75, 'Seed data: rule-based baseline (threshold x3) - current stock, minimum 1.', 'PENDING', 'INVENTORY_LOW', 'RULE_BASED', CURRENT_TIMESTAMP, NULL);
